Lesson 3
froggye/CAPIBARARA-hw pull request #2
Opened 2023-11-16 10:04 UTC by froggye

2023-11-21 02:05 UTC, WelcomeDev requested changes

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/contacts.js
> +    mail.href = "javascript:void(0)";
Я предлагаю оставить пустой href (undefined) или #, если ты хочешь сохранить курсор

Вообще это задание довольно синтетическое. Обычно никто не занимается такой фигней, что поведение на мобилке и десктопе отличается. Обычно это всегда стандартные mailto, tel

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/contacts.js
> +        void copyText(mail);
а зачем тут void? И так замечательно будет работать

Я знаю только один уместный кейс применения void, это когда пишешь iife

```js
// этот вариант словно короче, но более загадочный. Поэтому я его никогда даже не использую. Потому что не все знают про оператор void 
void function(){
}()
// or
// это немного не так удобно писать, потому что всю функцию нужно обернуть в `()`, но по-моему, понятнее
(function(){
})()
```

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/experience.js
> +    date.classList.add('body2');
Можно сократить до date.className='body2 drop-shadow--md...'

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/experience.js
> +    let content =
боньк 99 уровня. В JS есть string interpolation

`<img src="static"></img><p>${expTitles[i]}</p>`

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/header.js
> +    if (window.innerWidth > 768) {
лучше использовать fail-fast подход. Нужно инвертировать условие и сделать return, если оно true

`if(window.innerWidth<=768) return`

Посмотри также на такую штуку как `window.matchMedia`, это более оптимальный способ сделать это

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/skills.js
> +let skillsImages = [
зачем тут let? Ты не мутируешь ссылку

2023-11-21 02:05 UTC, WelcomeDev commented on static/scripts/skills.js
> +for (let i = 0; i < skillsDescr.length; ++i) {
Я бы объединил массивы в массив объектов или кортежей

```js
const data = [
    ['Js', 'icon-js.png']
]
// or
const data = [
 { desc: 'js', img: 'icon-js.png' }
]
```

```js
data.map(it=>{
  const li = document.createElement('li');
  // rest of logic
 return li;
}).forEach(it=>skillsList.append(it))
```

2023-11-22 08:34 UTC, sergio2O1 commented on static/css/experienceSection.css
> +
строчки лишние можно убрать

2023-11-22 09:03 UTC, sergio2O1 commented on static/scripts/contacts.js
> +    let details = navigator.userAgent;
если значение меняться не будет, объявляем `const`

2023-11-22 09:07 UTC, sergio2O1 commented on static/scripts/header.js
> +    if (header.classList.contains('menu-expanded')){
подобные конструкции

```js
if (condition) {
    res = 'TRUE_RESULT'
} else {
    res = 'FALSE_RESULT'
}
```

можно записать через тернарку

```js
res = condition
    ? 'TRUE_RESULT'
    : 'FALSE_RESULT'
```

2023-11-22 09:09 UTC, sergio2O1 commented on static/scripts/testimonials.js
> +let tesImages = [
еще раз, все что меняться не будет, объявляем через const

2023-11-22 09:10 UTC, sergio2O1 commented on static/scripts/experience.js
> +    for(let i = 0; i < expButtons.length; i++) {
пробел между for и скобкой

2023-11-22 09:16 UTC, sergio2O1 commented
в момент перехода по каждому из пунктов меню хотелось бы, чтобы еще менюшка сама закрывалась

2023-12-01 01:23 UTC, sergio2O1 approved these changes

2023-12-01 07:40 UTC, merged